
//Look up table for meda data (enum, options, etc)
Table meta {
    id int [pk, increment]
    key varchar [not null, unique, note:"key for the meta data, e.g, role_enum, caretaker_enum, etc"]
    value varchar [not null, note:"value for the meta data, e.g, head, deputy, accountant, treasurer, member for role_enum; mother, father, grandmother, grandfather, other for caretaker_enum"]
}
//

// to be put into the meta table
enum role_enum{
        head
        deputy
        accountant
        treasurer
        member
    }
//import from lao ethnicity master dataset
Table ethnicity {
    ethnicity_code varchar [pk,unique, not null, note:"unique identifier for ethinicity. e.g, 01.02"]
    ethno_linguistic_group_en varchar [not null, note:"ethno-linguistic group in English"]
    ethno_linguistic_group_la varchar [not null, note:"ethno-linguistic group in Laotiane"]
    ethnicity_en varchar [not null, note:"ethnicity name in English"]
    ethnicity_la varchar [not null, note:"ethnicity name in Laotiane"]
}
// will be linked to village profile_detail table in the future.
table village_profile {
  village_id char(7) [pk, unique, not null, note:"unique identifier for each village, format: province_code + district_code + village_code. 6-7 digits code, e.g, 0102003"]
  village_name varchar 
  district_name varchar
  province_name varchar
  batch int [not null, note:"implementation batch of the village, 1 or 2"]
  //temporaty
}
//village_id will be used as a basis for creating group id, member id, and other ids in the future. 
//It will be a 7 character code, where the first 2 characters represent the province code, 
//the next 2 characters represent the district code, and the last 3 characters represent the village code.
//For example, if a village is located in province 01, district 02, and has a village code of 003, then the village_code will be "0102003".
table group{
    group_id varchar [not null, note:"unique id for each group. group_id will be generated as province_code - district_code - village_code - batch - group_type - group_number"]
    village_id char(7) [not null, ref: < village_profile.village_id, note:"foreign key referencing village profile id"]
    name varchar [null, note:"name of the group, nullable"]
    group_type varchar [not null, note:"type of the group, either SHG or CNG; Others such as VSMC, VDP can also be added"]
    date_created date [not null, note:"date when the group was created"]
    isActive boolean [default: true, note:"indicates whether the group is currently active"]
    isApproved boolean [default: false, note:"indicates whether the group has been approved by the project team"]
    created_at timestamp [default: `now()`, note:"timestamp when the group was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the group was last updated"]
}
// calculate on the fly: 1. NLT (Non-Lao-Tai) via joining with ethnicity table
table member_shg{
    member_id varchar [pk,unique, not null, note:"unique member id for each member. e.g, group_id - member_number"]
    group_id varchar [not null, ref: > group.group_id, note:"foreign key referencing group id"]
    name varchar [not null]
    gender char(1) [not null, note:"{M,F}"]
    role role_enum [not null, note:"role of the member in the SHG"]
    ethinicity_code int [not null, ref: < ethnicity.ethnicity_code, note:"ethnicity of the member, reference to ethnicity table"]
    join_date date [not null, note:"date when the member joined the SHG"]
    isActive boolean [default: true, note:"indicates whether the member is currently active in the SHG"]
    created_at timestamp [default: `now()`, note:"timestamp when the member was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the member was last updated"]
}
// cng member status will be calculated on the fly based on dob and join_date for child, and based on
// child's status and mother's role in cng
table member_cng{
    member_id varchar [pk, unique, not null, note:"unique member id for each member"]
    group_id varchar [not null, ref: > group.group_id, note:"foreign key referencing group id"]
    name varchar [not null]
    role role_enum [not null, note:"role of the member in the CNG"]
    ethinicity_code int [not null, ref: < ethnicity.ethnicity_code, note:"ethnicity of the member, reference to ethnicity table"]
    shg_member_id varchar [not null, ref: < member_shg.member_id, note:"foreign key referencing member id in member_shg table, to link the cng member with the shg member"]
    join_date date [not null, note:"date when the child joined the CNG"]
    created_at timestamp [default: `now()`, note:"timestamp when the member was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the member was last updated"]
}
// to be put into the meta table
enum caretaker_enum{
    mother
    father
    grandmother
    grandfather
    other
}
//ethnicity_code will be derived from mother_ethnicity in cng member table, and will be used to calculate NLT status for the child.
//
table member_cng_child{
    member_id varchar [pk, unique, not null, note:"unique member id for each member. e.g, mother_id + child_number"]
    mother_id varchar [not null, ref: > member_cng.member_id, note:"foreign key referencing mother id in member_cng table"]
    name varchar [not null]
    dob date [not null, note: "date of birth of the child"]
    gender char(1) [not null, note:"{M,F}"]
    ethinicity_code int [not null, ref: < ethnicity.ethnicity_code, note:"ethnicity of the member, reference to ethnicity table"]
    caretaker caretaker_enum [not null, note:"caretaker of the child, either mother or other family member"]
    join_date date [not null, note:"date when the child joined the CNG"]
    created_at timestamp [default: `now()`, note:"timestamp when the member was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the member was last updated"]
    }

// Below are tables for loan, saving and transaction, which will be used to track the financial activities of the SHG members.
// status: active, closed, defaulted, etc. will be calculated on the fly based on the loan repayment records and end_date of the loan.
Table loan_account{
    id varchar [pk, unique, not null, note:"unique identifier for each loan. e.g, member_id - loan_number"]
    member_id varchar [not null, ref: > member_shg.member_id, note:"foreign key referencing member id in member_shg table"]
    loan_source varchar [not null, note:"source of the loan, {seed grant, group revolving fund (GRF) and Revolving Loan Fund (RLF)}"]
    loan_category varchar [not null, note:"type of the loan, e.g, chicken raising, pig raising, etc"]
    principal decimal(10,2) [not null, note:"principal amount of the loan"]
    interest_rate decimal(5,2) [not null, note:"interest rate of the loan per year"]
    term int [not null, note:"term of the loan in months"]
    start_date date [not null, note:"start date of the loan"]
    end_date date [not null, note:"end date of the loan , calculated as start_date + term"]
    close_date date [null, note:"date when the loan was closed, nullable until the loan is closed"]   
    note varchar [null, note:"additional note for the loan, nullable"]
    created_at timestamp [default: `now()`, note:"timestamp when the loan was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the loan was last updated"]
}

// repayment records will be used to track the repayment activities of the loan. Each record represents a repayment made by the member for a specific loan. The status of the loan (active, closed, defaulted, etc.) can be calculated on the fly based on the repayment records and the end_date of the loan.
// For example, if the loan has a repayment record with payment_date and the total amount repaid (principal_repaid + interest_repaid) is equal to or greater than the total amount due (principal + interest), then the loan can be marked as closed. If the current date is past the end_date and the loan is not fully repaid, then the loan can be marked as defaulted.
// total amount paid will be calculated on query
Table loan_repayment {
    id int [pk, increment]
    loan_id varchar [not null, ref: > loan_account.id, note:"foreign key referencing loan id in loan_account table"]
    principal_repaid decimal(10,2) [not null, note:"principal amount repaid in this repayment"]
    interest_repaid decimal(10,2) [not null, note:"interest amount repaid in this repayment"]
    payment_date date [not null, note:"date when the repayment was made"]
    note varchar [null, note:"additional note for the repayment, nullable"]
    created_at timestamp [default: `now()`, note:"timestamp when the loan repayment was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the loan repayment was last updated"]
}
 Table saving_account {
    account_id varchar [pk, not null, ref: > member_shg.member_id, note:"foreign key referencing member id in member_shg table, shared primary key to ensure one saving account per member"]
    balance decimal(10,2) [not null, default: 0.00, note:"current balance of the saving account. needed to be updated on each saving transaction by triggering"]
    interest_rate decimal(5,2) [not null, note:"interest rate of the saving account per year"]
    note varchar [null, note:"additional note for the saving account, nullable"]
    created_at timestamp [default: `now()`, note:"timestamp when the saving account was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the saving account was last updated"]
 }
// on opening account, one transaction record will be created with amount = 0 to indicate the opening of the account. 
 Table saving_transaction {
    id int [pk, increment, note:"unique identifier for each saving transaction"]
    account_id varchar [not null, ref: > saving_account.account_id, note:"foreign key referencing saving account id in saving_account table"]
    amount decimal(10,2) [not null, note:"amount of the transaction, positive for deposit and negative for withdrawal"]
    transaction_date date [not null, note:"date when the transaction was made"]
    note varchar [null, note:"additional note for the saving transaction, nullable"]
    created_at timestamp [default: `now()`, note:"timestamp when the saving transaction was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the saving transaction was last updated"]
 }


//CRI CLUSTER STARTS HERE
table cri_village_priority{
    id int [pk, increment, note:"unique identifier for each village priority record"]
    village_id char(7) [not null, ref: < village_profile.village_id, note:"foreign key referencing village profile id"]
    category varchar [not null, note:"category of the cri; controlled list; to be linked to meta table*"]
    cri_type varchar [not null, note:"type of the CRI; controlled list; to be linked to meta table*"]
    priority int [not null, note:"priority level of the CRI, e.g, 1 for highest priority, 2 for second priority, etc"]
    uom varchar [not null, note:"unit of measurement for the CRI; controlled list; to be linked to meta table*"]
    dim varchar [not null, note:"dimension of the CRI"]
    unit_cost decimal(10,2) [not null, note:"unit cost for addressing the CRI"]
    cri_count int [not null, note:"number of CRI of the same type to be addressed"]
    total_cost decimal(10,2) [not null, note:"total cost for addressing the CRI"]
    cri_selector varchar [not null, note:"selector (group) for the CRI, e.g, male, male over 14, etc"]
    created_at timestamp [default: `now()`, note:"timestamp when the village priority record was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the village priority record was last updated"]
    note: 
    '''this table will be used to store submission data from ENG_01;
    it is intended to be static and will be updated by batch.'''
}

table cri_registration{
    cri_id varchar [pk, not null, unique, note:"unique code for each CRI, format: village_code - batch - cri_type - cri_number. e.g, 0102003-1-IRR-1"]
    village_id char(7) [not null, ref: < village_profile.village_id, note:"foreign key referencing village profile id"]
    cri_category varchar [not null, note:"category of the cri; controlled list; to be linked to meta table"]
    cri_type varchar [not null, note:"type of the CRI; controlled list; to be linked to meta table"]
    cri_number int [not null, note:"given number of the CRI"]
    geo_location point [not null, note:"geographical location of the CRI; to be implemented as geopoint datatype in db"]
    total_cost decimal(10,2) [not null, note:"total cost for addressing the CRI"]
    budget_clear varchar [not null, note:"CLEAR approved budget for the CRI"]
    budget_community varchar [not null, note:"community contribution for the CRI, either in cash or in kind"]
    direct_beneficiary_total varchar [not null, note:"direct beneficiary of the CRI"]
    direct_beneficiary_female int [not null, note:"number of female direct beneficiaries of the CRI"]
    direct_beneficiary_NLT int [not null, note:"number of Non-Lao-Tai direct beneficiaries of the CRI"]
    travel_time_saved int [not null, note:"estimated travel time saved after addressing the CRI, in minutes"]
    note:
    '''this table will be used to store the CRI registration data from ENG_03 CRI Registration (formerly CRI activity proposal) form.;
    input data will be available upon final VDP (village development plan) approved, which is about 3 months after the submision of village priority.'''
}

table cri_registration_details{
    cri_id varchar [not null, ref: - cri_registration.cri_id, note:"foreign key referencing cri_id in cri_registration table; one-to-one"]
    cri_details jsonb [not null, note:"detailed description of the CRI; this field will store the full json data from KoboToolbox submission."]
    note:
    '''This table wil be used as a reference for the detailed information of the CRI. it will not be queried frequently.'''
}


table cri_progress{
    cri_id varchar [not null, ref: > cri_registration.cri_id, note:"foreign key referencing cri_id in cri_registration table"]
    progress int [not null, note:"progress percentage for addressing the CRI, from 0 to 100"]
    note varchar [not null, note:"additional note for the CRI progress; info such as completed tasks + quality, observations, reason for no progress from the previous record, etc"]
    progress_date date [not null, note:"date when the progress record was created"]
    note:
    '''this table will be used to track the progress of addressing the CRI. Each record represents a progress update for a specific CRI. 
    The progress percentage will be updated on each update, and the note field will be used to provide additional information about the progress, 
    especially when there is no progress from the previous record, e.g, due to delay in procurement, etc.'''

}


// NUT modules
// powder management is recorded by group
Table nut_powder_management{
    id int [pk, increment, note:"unique identifier for each powder management record"]
    group_id varchar [not null, ref: > group.group_id, note:"foreign key referencing group id in group table"]
    meeting_date date [not null, note:"date of the meeting"]
    members_in_village int [not null, note:"ຈຳນວນ ສະມາຊິກ ກພຊ ທັງໝົດພາຍໃນບ້ານ"]
    total_participants int [not null, note:"total number of participants in the cng meetings"]
    food_supported_families int [not null, note:"number of poor families receiving food support through cng meetings"]
    food_money decimal(13,2) [not null, note: "ຈຳນວນເງິນຊື້ອາຫານ (ກີບ)"]
    food_from_shg decimal(13,2) [not null, note:"quantity of food received from SHG for powder management, in LAK"]
    produced_powders jsonb [not null, note:"quantities of powders produced in the month, keyed by type; example: {rice: 10.2, vegetable: 5, fish: 2, meat: 1, legume: 4, other: 0}"]
    shared_powders jsonb [not null, note:"quantities of powders shared to non-cng in the month, keyed by type; example: {rice: 10, vegetable: 5.1, fish: 2, meat: 1, legume: 4, other: 0}"]
    grinder_used_cngs int [not null, note:"number of CNG members using the grinder for powder making in the month"]
    grinder_produced_powder decimal(5,2) [not null, note:"quantity of powder produced by using the grinder in the month, in kg"]
    community_contributed_food decimal(13,2) [not null, note:"Estimated value of food contributed by the community for powder management in the month, in LAK"]
    support_undernutrition decimal(13,2) [not null, note:" amount of money for powder production for undernutritious children"]
    created_at timestamp [default: `now()`, note:"timestamp when the powder management record was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the powder management record was last updated"]
}
// Goat Dairy Shadehouse, HNG, MMPL, HH visit, and NTFP are moinitored by group; fq is monthly
// nut_monthly_update store Shadehouse, HNG, MMPL and HH visit
Table nut_monthly_update{
    id int [pk, increment, note:"unique identifier for each monthly data record"]
    group_id varchar [not null, ref: > group.group_id, note:"foreign key referencing group id in group table"]
    // Goat Dairy
    //ຈ.ນ ຜູ້ຊ່ວຍດ້ານກິດຈະກຳຮິດນົມແບ້ບ້ານ ໄດ້ຮັບການຝືກອົບຮົມຈາກ ຟາມຄວາຍຫຼວງພະບາງ
    //ຈຳນວນ ຄອບຄົວ ທີ່ໄດ້ຮັບການຝືກອົບຮົມການລ້ຽງແບ້ຮິດເອົານົມຈາກທາງກະສິກອນຕົວແບບ
    //ຈ.ນ ນ້ຳນົມທີ່ຮິດໄດ້ທັງໝົດ(ລິດ)
    //ຈ.ນ ນ້ຳນົມທີ່ໄດ້ຂາຍໃຫ້ກຸ່ມໂພຊະນາການ(ລິດ)
    //ຈ.ນ ຄອບຄົວທີ່ໄດ້ເຮັດໃບມັນຕົ້ນໝັກ
    count_trained_milking int [not null]
    count_trained_hh int [not null, note: "number of families trained in Goat Dairy"]
    amount_milk decimal(5,2) [not null, note: "Milk produced in Litre"]
    amount_sold decimal(5,2) [not null, note: "in Litre; amount sold to CNG"]
    count_families_cassava_fermentation int [not null, note:"number of families engage in fermentation of cassava leaves"]
    // Shadehouse
    //ຈ.ນ ຄອບຄົວຕົວແບບທີ່ໄດ້ຮັບການຝືກອົບຮົມເຮືອນຮົ່ມຈາກສະມາຄົມກະສິກອນລາວ 	
    //ນ ເຮືອນຮົ່ມຊຸມຊົນທີ່ໄດ້ສ້າງຂື້ນ
    //ຈ.ນ ຊະມາຊິກ ກພຊ ເຂົ້າຮ່ວມຝືກອົບຮົມໂດຍກະສິກອນຕົວແບບ
    //ຈຳນວນຜັກທີ່ຜະລິດໄດ້ທັງໝົດ(ກີບຕໍ່ເດືອນ)
    //ຈຳນວນຜັກທີນຳມາປຸງແຕ່ງອາຫານໃນກອງປະຊຸມກຸ່ມໂພຊະນາການ(ກີບຕໍ່ເດືອນ)
    //ຈຳນວນຜັກທັງໝົດທີ່ໄດ້ຂາຍ( ກີບຕໍ່ເດືອນ)
    shadehouse_model_farmers int [not null, note:"number of model farmers trained for shadehouse in the month"]
    shadehouses_constructed int [not null, note:"number of shadehouses constructed in the month"]
    cng_trained_by_model_farmers int [not null, note:"number of CNG members trained by model farmers in the month"]
    veg_produced int [not null, note:"quantity of vegetables produced in the month, in LAK"]
    veg_used_in_meetings int [not null, note:"quantity of vegetables used in CNG meetings in the month, in LAK"]
    veg_sold int [not null, note:"quantity of vegetables sold in the month, in LAK"]
    // HNG
    //ຈ.ນ ກະສິກອນຕົວແບບທີ່ໄດ້ຮັບການຝືກອົບຮົມສວນຄົວຈາກສະມາຄົມກະສິກອນລາວ ພືດລະດູແລ້ວ ແລະ ຝົນ	
    //ຈ.ນ ຝືກສວນຄົວໃຫ້ກັບຊະມາຊິກ ກພຊ ໂດຍກະສິກອນຕົວແບບ	
    //ຈ.ນ ສະມາຊິກ ກພຊ ເຂົ້າຮ່ວມຝືກອົບຮົມ	
    //ຈ.ນ ຄອບຄົວທີ່ປູກຜັກຢ່າງໜ້ອຍ 3 ຊະນິດທີ່ໂຄງການສະໜອງໃຫ້
    hng_model_farmers int [not null, note:"number of model farmers trained in the month"]
    hng_trainings_conducted int [not null, note:"number of HNG training sessions conducted in the month"]
    training_participants int [not null, note:"number of training participants in the month"]
    tri_crops_households int [not null, note:"number of households practicing triple cropping in the month"]
    // MMPL
    //ຈ.ນ ກະສິກອນຕົວແບບທີ່ໄດ້ຮັບການຝືກອົບຮົມການສ້າງວິດີໂອໂດຍທາງບໍລິສັດຄລິກ
    //ຈ.ນ ວິດີໂອທີ່ສາມາດຜະລິດໃນເດືອນ
    //ຈ.ນ ວິດີໂອທີ່ດ້ຮັບອະນຸມັດຈາກບໍລິສັດຄລິກ
    //ຈ.ນ ວິດີໂອທີ່ໄດ້ເຜີຍແຜ່ໃນອອນໄລ-ເຟສບຸກ
    //ຈ.ນ ວິດີໂອທີ່ໄດ້ເຜີຍແຜ່ໃນອອນໄລ-ຢູທູບ
    //ຈ.ນ ວິດີໂອທີ່ໄດ້ເຜີຍແຜ່ໃນອອນໄລ-ທິກທັອກ
    //ຈ.ນ ວິດີໂອທີ່ໄດ້ເຜີຍແຜ່ໃນອອນໄລ-ວັອດແອັບ
    count_trained_model_farmers int [not null,note: "number of model farmers trained by CLICK in the month"]
    count_video_produced int [not null]
    count_video_approved int [not null]
    count_dissemminated_fb int [not null]
    count_dissemminated_yt int [not null]
    count_dissemminated_tiktok int [not null]
    count_dissemminated_whatsapp int [not null]
    // Garden visit
    //ວັນທີ, ເດືອນ, ປີ ລົງຢ້ຽມຢາມ	
    //ຈ.ນ ຄົວເຮືອນທັງໝົດທີ່ໄດ້ຢ້ຽມຢາມໂດຍກະສິກອນຕົວແບບ
    visit_date date [not null, note:"visit dates"]
    visited_hh int [not null, note:"number of households visited during the garden visits in the month"]
    created_at timestamp [default: `now()`, note:"timestamp when the monthly data record was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the monthly data record was last updated"]
}

// to store meeting data
// can be used for: NUT-NTFP meeting, NUT-Community Meeting (6-monthly)
Table meetings{
    id int [pk, increment, note:"unique identifier for each meeting record"]
    //NUT - NTFP meeting
    group_id varchar [not null, ref: > group.group_id, note:"foreign key referencing group id in group table"]
    meeting_type varchar [not null, note:"type of the meeting, e.g, NUT-NTFP meeting, NUT-Community Meeting (6-monthly); the list should be dynamic"]
    training_date int [not null, note:"date the training/meeting was conducted"]
    participants int [not null, note:"totalnumber of participants in the meetings"]
    female_participants int [not null, note:"total number of female participants in the meetings"]
    record_note varchar [null, note:"additional note for the meeting, nullable"]
    created_at timestamp [default: `now()`, note:"timestamp when the meeting record was created"]
    updated_at timestamp [default: `now()`, note:"timestamp when the meeting record was last updated"]
}